### ISSUE TITLE
 pointwise.glyph_client.GlyphError: can't find package PWI_Glyph 

### ISSUE THREAD

**Issue by Jimmyenricohu** [pointwise/GlyphClientPython#4]
Dear Sir, thank you for sharing this package. I got some problem, when I try to excute the script in the folder "example". It said that pointwise and glyph_client.py couldn't find the "PWI_GLyph" package. 
And "Could not load Glyph package. Ensure that the Pointwise version of tclsh is the only one in your PATH. "
In actually, I have add the package location in the environment variable. 
Could you help me to find out the way to solve this problem? 
Seeking for your feedbacks.Thank you

**Comment by pabakertx** [comment]
There are not many details to go on here, but if you are, say, running on Windows and have Pointwise (not the python client) installed somewhere like "c:\Program Files\Cadence\FidelityPointwise2022.2", then you need to add "c:\Program Files\Cadence\FidelityPointwise2022.2\win64\bin" to your PATH before creating your GlyphClient object so that the python client can find 'tclsh.exe' in the Pointwise installation directory. This assumes that you (a) have a valid Pointwise license available and (b) do not want to connect to a running instance of Pointwise. See the README for details on how to connect to a running instance of Pointwise via the Glyph Server.
